function A = A_DIP(in1,in2)
%A_DIP
%    A = A_DIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    24-Apr-2026 11:16:38

L1 = in2(1,:);
c1 = in2(3,:);
c2 = in2(4,:);
j1 = in2(7,:);
j2 = in2(8,:);
m1 = in2(5,:);
m2 = in2(6,:);
th2 = in1(2,:);
t2 = cos(th2);
t3 = c2.^2;
t4 = m2.*t3;
t5 = L1.*c2.*m2.*t2;
t6 = j2+t4+t5;
A = reshape([j1+t5+t6+L1.^2.*m2+c1.^2.*m1,t6,t6,j2+t4],[2,2]);
end
