function A_lin_sym = Alin_DIP(in1)
%Alin_DIP
%    A_lin_sym = Alin_DIP(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    24-Apr-2026 11:16:39

L1 = in1(1,:);
c1 = in1(3,:);
c2 = in1(4,:);
j1 = in1(7,:);
j2 = in1(8,:);
m1 = in1(5,:);
m2 = in1(6,:);
t2 = j1.*j2;
t3 = L1.^2;
t4 = c1.^2;
t5 = c2.^2;
t6 = L1.*j2.*m2;
t7 = c1.*j2.*m1;
t8 = j2.*m2.*t3;
t9 = j2.*m1.*t4;
t10 = j1.*m2.*t5;
t11 = c1.*m1.*m2.*t5;
t12 = m1.*m2.*t4.*t5;
t13 = t2+t8+t9+t10+t12;
t14 = 1.0./t13;
A_lin_sym = reshape([0.0,0.0,t14.*(t6+t7+t11).*(9.81e+2./1.0e+2),t14.*(t6+t7+t11-c2.*j1.*m2-c2.*m1.*m2.*t4+L1.*c1.*c2.*m1.*m2).*(-9.81e+2./1.0e+2),0.0,0.0,L1.*m2.^2.*t5.*t14.*(-9.81e+2./1.0e+2),c2.*m2.*t14.*(j1+m1.*t4+m2.*t3+L1.*c2.*m2).*(9.81e+2./1.0e+2),1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0],[4,4]);
end
