function b = b_DIP(in1,in2,in3)
%b_DIP
%    B = b_DIP(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    03-May-2026 22:57:41

L1 = in3(1,:);
c1 = in3(3,:);
c2 = in3(4,:);
dth1 = in1(3,:);
dth2 = in1(4,:);
m1 = in3(5,:);
m2 = in3(6,:);
tau1 = in2(1,:);
tau2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = sin(th1);
t3 = sin(th2);
t4 = th1+th2;
t5 = sin(t4);
b = [tau1+m2.*(L1.*t2+c2.*t5).*(9.81e+2./1.0e+2)+dth2.*(L1.*c2.*dth1.*m2.*t3.*2.0+L1.*c2.*dth2.*m2.*t3)+c1.*m1.*t2.*(9.81e+2./1.0e+2);tau2+c2.*m2.*t5.*(9.81e+2./1.0e+2)-L1.*c2.*dth1.^2.*m2.*t3];
end
