function B_lin_sym = Blin_DIP(in1)
%Blin_DIP
%    B_lin_sym = Blin_DIP(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    03-May-2026 22:57:42

L1 = in1(1,:);
c1 = in1(3,:);
c2 = in1(4,:);
j1 = in1(7,:);
j2 = in1(8,:);
m1 = in1(5,:);
m2 = in1(6,:);
t2 = j1.*j2;
t3 = L1.^2;
t4 = c1.^2;
t5 = c2.^2;
t6 = L1.*c2.*m2;
t7 = m2.*t5;
t8 = j2.*m2.*t3;
t9 = j2.*m1.*t4;
t10 = j1.*t7;
t11 = m1.*t4.*t7;
t12 = j2+t6+t7;
t13 = t2+t8+t9+t10+t11;
t14 = 1.0./t13;
t15 = t12.*t14;
t16 = -t15;
B_lin_sym = reshape([0.0,0.0,t14.*(j2+t7),t16,0.0,0.0,t16,t14.*(j1+t6+t12+m1.*t4+m2.*t3)],[4,2]);
end
