function CoM_pos = CoM_pos_DIP(in1,in2)
%CoM_pos_DIP
%    CoM_pos = CoM_pos_DIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    11-May-2026 11:17:42

L1 = in2(1,:);
c1 = in2(3,:);
c2 = in2(4,:);
m1 = in2(5,:);
m2 = in2(6,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = m1+m2;
t5 = th1+th2;
t6 = 1.0./t4;
CoM_pos = [-t6.*(m2.*(L1.*t3+c2.*sin(t5))+c1.*m1.*t3);t6.*(m2.*(L1.*t2+c2.*cos(t5))+c1.*m1.*t2)];
end
