function DJ_CoM = DJ_CoM_DIP(in1,in2)
%DJ_CoM_DIP
%    DJ_CoM = DJ_CoM_DIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    21-Apr-2026 09:59:21

dth1 = in1(3,:);
dth2 = in1(4,:);
l_Am2 = in2(4,:);
l_OA = in2(1,:);
l_Om1 = in2(3,:);
m1 = in2(5,:);
m2 = in2(6,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = m1+m2;
t5 = th1+th2;
t6 = cos(t5);
t7 = sin(t5);
t8 = 1.0./t4;
t9 = dth2.*l_Am2.*m2.*t6.*t8;
t10 = dth2.*l_Am2.*m2.*t7.*t8;
t11 = -t9;
t12 = -t10;
DJ_CoM = reshape([t12-dth1.*t8.*(m2.*(l_Am2.*t7+l_OA.*t3)+l_Om1.*m1.*t3),t11-dth1.*t8.*(m2.*(l_Am2.*t6+l_OA.*t2)+l_Om1.*m1.*t2),t12-dth1.*l_Am2.*m2.*t7.*t8,t11-dth1.*l_Am2.*m2.*t6.*t8],[2,2]);
end
