function DJ_CoM = DJ_CoM_DIP(in1,in2)
%DJ_CoM_DIP
%    DJ_CoM = DJ_CoM_DIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    03-May-2026 22:57:42

L1 = in2(1,:);
c1 = in2(3,:);
c2 = in2(4,:);
dth1 = in1(3,:);
dth2 = in1(4,:);
m1 = in2(5,:);
m2 = in2(6,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = m1+m2;
t5 = th1+th2;
t6 = cos(t5);
t7 = sin(t5);
t8 = 1.0./t4;
t9 = c2.*dth2.*m2.*t6.*t8;
t10 = c2.*dth2.*m2.*t7.*t8;
t11 = -t9;
t12 = -t10;
DJ_CoM = reshape([t12-dth1.*t8.*(m2.*(L1.*t3+c2.*t7)+c1.*m1.*t3),t11-dth1.*t8.*(m2.*(L1.*t2+c2.*t6)+c1.*m1.*t2),t12-c2.*dth1.*m2.*t7.*t8,t11-c2.*dth1.*m2.*t6.*t8],[2,2]);
end
