function dr = dr_DIP(in1,in2)
%dr_DIP
%    DR = dr_DIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    11-May-2026 11:17:41

L1 = in2(1,:);
L2 = in2(2,:);
dth1 = in1(3,:);
dth2 = in1(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = cos(t4);
t6 = sin(t4);
dr = [0.0;0.0;-L1.*dth1.*t2;-L1.*dth1.*t3;-dth1.*(L1.*t2+L2.*t5)-L2.*dth2.*t5;-dth1.*(L1.*t3+L2.*t6)-L2.*dth2.*t6];
end
