function dr = dr_DIP(in1,in2)
%dr_DIP
%    DR = dr_DIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    18-Mar-2026 09:55:46

dth1 = in1(3,:);
dth2 = in1(4,:);
l_AB = in2(2,:);
l_OA = in2(1,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = cos(t4);
t6 = sin(t4);
dr = [0.0;0.0;dth1.*l_OA.*t2;-dth1.*l_OA.*t3;dth1.*(l_AB.*t5+l_OA.*t2)+dth2.*l_AB.*t5;-dth1.*(l_AB.*t6+l_OA.*t3)-dth2.*l_AB.*t6];
end
