function E = E_DIP(in1,in2)
%E_DIP
%    E = E_DIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    01-May-2026 02:35:45

L1 = in2(1,:);
c1 = in2(3,:);
c2 = in2(4,:);
dth1 = in1(3,:);
dth2 = in1(4,:);
j1 = in2(7,:);
j2 = in2(8,:);
m1 = in2(5,:);
m2 = in2(6,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = cos(th2);
t4 = c2.^2;
t5 = dth1.^2;
t6 = dth2.^2;
E = (j1.*t5)./2.0+(j2.*t5)./2.0+(j2.*t6)./2.0+m2.*(L1.*t2+c2.*cos(th1+th2)).*(9.81e+2./1.0e+2)+(c1.^2.*m1.*t5)./2.0+dth1.*dth2.*j2+c1.*m1.*t2.*(9.81e+2./1.0e+2)+(m2.*t4.*t5)./2.0+(m2.*t4.*t6)./2.0+(L1.^2.*m2.*t5)./2.0+dth1.*dth2.*m2.*t4+L1.*c2.*m2.*t3.*t5+L1.*c2.*dth1.*dth2.*m2.*t3;
end
