function E = E_DIP(in1,in2)
%E_DIP
%    E = E_DIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    18-Mar-2026 09:55:46

I1 = in2(7,:);
I2 = in2(8,:);
dth1 = in1(3,:);
dth2 = in1(4,:);
g = in2(9,:);
l_Am2 = in2(4,:);
l_OA = in2(1,:);
l_Om1 = in2(3,:);
m1 = in2(5,:);
m2 = in2(6,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = cos(th2);
t4 = dth1.^2;
t5 = dth2.^2;
t6 = l_Am2.^2;
E = (I1.*t4)./2.0+(I2.*t4)./2.0+(I2.*t5)./2.0+(l_OA.^2.*m2.*t4)./2.0+(l_Om1.^2.*m1.*t4)./2.0+g.*m2.*(l_OA.*t2+l_Am2.*cos(th1+th2))+I2.*dth1.*dth2+(m2.*t4.*t6)./2.0+(m2.*t5.*t6)./2.0+dth1.*dth2.*m2.*t6+g.*l_Om1.*m1.*t2+l_Am2.*l_OA.*m2.*t3.*t4+dth1.*dth2.*l_Am2.*l_OA.*m2.*t3;
end
