function head_pos = head_pos_DIP(in1,in2)
%head_pos_DIP
%    HEAD_POS = head_pos_DIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    01-May-2026 02:35:46

L1 = in2(1,:);
L2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
head_pos = [L2.*sin(t2)+L1.*sin(th1);L2.*cos(t2)+L1.*cos(th1)];
end
