function hip_pos = hip_pos_DIP(in1,in2)
%hip_pos_DIP
%    HIP_POS = hip_pos_DIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    11-May-2026 11:17:42

L1 = in2(1,:);
th1 = in1(1,:);
hip_pos = [-L1.*sin(th1);L1.*cos(th1)];
end
