function J_CoM = J_CoM_DIP(in1,in2)
%J_CoM_DIP
%    J_CoM = J_CoM_DIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    24-Apr-2026 11:16:40

L1 = in2(1,:);
c1 = in2(3,:);
c2 = in2(4,:);
m1 = in2(5,:);
m2 = in2(6,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = m1+m2;
t5 = th1+th2;
t6 = cos(t5);
t7 = sin(t5);
t8 = 1.0./t4;
J_CoM = reshape([t8.*(m2.*(L1.*t2+c2.*t6)+c1.*m1.*t2),-t8.*(m2.*(L1.*t3+c2.*t7)+c1.*m1.*t3),c2.*m2.*t6.*t8,-c2.*m2.*t7.*t8],[2,2]);
end
