function J_rA = J_rA_DIP(in1,in2)
%J_rA_DIP
%    J_rA = J_rA_DIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    03-May-2026 22:57:42

L1 = in2(1,:);
th1 = in1(1,:);
J_rA = reshape([L1.*cos(th1),-L1.*sin(th1),0.0,0.0],[2,2]);
end
