function J_rA = J_rA_DIP(in1,in2)
%J_rA_DIP
%    J_rA = J_rA_DIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    18-Mar-2026 09:55:46

l_OA = in2(1,:);
th1 = in1(1,:);
J_rA = reshape([l_OA.*cos(th1),-l_OA.*sin(th1),0.0,0.0],[2,2]);
end
