function J_rB = J_rB_DIP(in1,in2)
%J_rB_DIP
%    J_rB = J_rB_DIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    11-May-2026 11:17:41

L1 = in2(1,:);
L2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = sin(t2);
t5 = L2.*t3;
t6 = L2.*t4;
t7 = -t5;
t8 = -t6;
J_rB = reshape([t7-L1.*cos(th1),t8-L1.*sin(th1),t7,t8],[2,2]);
end
