function r = r_DIP(in1,in2)
%r_DIP
%    R = r_DIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    11-May-2026 11:17:41

L1 = in2(1,:);
L2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = L1.*t2;
t6 = L1.*t3;
t7 = -t6;
r = [0.0;0.0;t7;t5;t7-L2.*sin(t4);t5+L2.*cos(t4)];
end
