function r = r_DIP(in1,in2)
%r_DIP
%    R = r_DIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    18-Mar-2026 09:55:46

l_AB = in2(2,:);
l_OA = in2(1,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = l_OA.*t2;
t6 = l_OA.*t3;
r = [0.0;0.0;t6;t5;t6+l_AB.*sin(t4);t5+l_AB.*cos(t4)];
end
