function A = A_DIP(in1,in2)
%A_DIP
%    A = A_DIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    18-Mar-2026 09:55:46

I1 = in2(7,:);
I2 = in2(8,:);
l_Am2 = in2(4,:);
l_OA = in2(1,:);
l_Om1 = in2(3,:);
m1 = in2(5,:);
m2 = in2(6,:);
th2 = in1(2,:);
t2 = cos(th2);
t3 = l_Am2.^2;
t4 = m2.*t3;
t5 = l_Am2.*l_OA.*m2.*t2;
t6 = I2+t4+t5;
A = reshape([I1+t5+t6+l_OA.^2.*m2+l_Om1.^2.*m1,t6,t6,I2+t4],[2,2]);
end
