function A_lin_sym = Alin_DIP(in1)
%Alin_DIP
%    A_lin_sym = Alin_DIP(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    18-Mar-2026 09:55:46

I1 = in1(7,:);
I2 = in1(8,:);
g = in1(9,:);
l_Am2 = in1(4,:);
l_OA = in1(1,:);
l_Om1 = in1(3,:);
m1 = in1(5,:);
m2 = in1(6,:);
t2 = l_Am2.^2;
t3 = l_OA.^2;
t4 = l_Om1.^2;
t5 = I1.*I2;
t6 = I2.*l_OA.*m2;
t7 = I2.*l_Om1.*m1;
t8 = I1.*m2.*t2;
t9 = I2.*m2.*t3;
t10 = I2.*m1.*t4;
t11 = l_Om1.*m1.*m2.*t2;
t12 = m1.*m2.*t2.*t4;
t13 = t5+t8+t9+t10+t12;
t14 = 1.0./t13;
A_lin_sym = reshape([0.0,0.0,g.*t14.*(t6+t7+t11),-g.*t14.*(t6+t7+t11-I1.*l_Am2.*m2-l_Am2.*m1.*m2.*t4+l_Am2.*l_OA.*l_Om1.*m1.*m2),0.0,0.0,-g.*l_OA.*m2.^2.*t2.*t14,g.*l_Am2.*m2.*t14.*(I1+m1.*t4+m2.*t3+l_Am2.*l_OA.*m2),1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0],[4,4]);
end
