function b = b_DIP(in1,in2,in3)
%b_DIP
%    B = b_DIP(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    18-Mar-2026 09:55:46

dth1 = in1(3,:);
dth2 = in1(4,:);
g = in3(9,:);
l_Am2 = in3(4,:);
l_OA = in3(1,:);
l_Om1 = in3(3,:);
m1 = in3(5,:);
m2 = in3(6,:);
tau1 = in2(1,:);
tau2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = sin(th1);
t3 = sin(th2);
t4 = th1+th2;
t5 = sin(t4);
b = [tau1+dth2.*(dth1.*l_Am2.*l_OA.*m2.*t3.*2.0+dth2.*l_Am2.*l_OA.*m2.*t3)+g.*m2.*(l_Am2.*t5+l_OA.*t2)+g.*l_Om1.*m1.*t2;tau2+g.*l_Am2.*m2.*t5-dth1.^2.*l_Am2.*l_OA.*m2.*t3];
end
