function B_lin_sym = Blin_DIP(in1)
%Blin_DIP
%    B_lin_sym = Blin_DIP(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    18-Mar-2026 09:55:46

I1 = in1(7,:);
I2 = in1(8,:);
l_Am2 = in1(4,:);
l_OA = in1(1,:);
l_Om1 = in1(3,:);
m1 = in1(5,:);
m2 = in1(6,:);
t2 = l_Am2.^2;
t3 = l_OA.^2;
t4 = l_Om1.^2;
t5 = I1.*I2;
t6 = l_Am2.*l_OA.*m2;
t7 = m2.*t2;
t9 = I2.*m2.*t3;
t10 = I2.*m1.*t4;
t8 = I1.*t7;
t11 = m1.*t4.*t7;
t12 = I2+t6+t7;
t13 = t5+t8+t9+t10+t11;
t14 = 1.0./t13;
t15 = t12.*t14;
t16 = -t15;
B_lin_sym = reshape([0.0,0.0,t14.*(I2+t7),t16,0.0,0.0,t16,t14.*(I1+t6+t12+m1.*t4+m2.*t3)],[4,2]);
end
