function J_rB = J_rB_DIP(in1,in2)
%J_rB_DIP
%    J_rB = J_rB_DIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    18-Mar-2026 09:55:47

l_AB = in2(2,:);
l_OA = in2(1,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = sin(t2);
t5 = l_AB.*t3;
t6 = l_AB.*t4;
t7 = -t6;
J_rB = reshape([t5+l_OA.*cos(th1),t7-l_OA.*sin(th1),t5,t7],[2,2]);
end
